routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('staffs', 'StaffController');
Route::resource('departments', 'DepartmentController');

Route::get('reports/departmentStafflist', 'DepartmentStaffController@index')->name('reports.departmentStaffList');

app/Http/Controllers/StaffController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Entities\Staff;
use App\Entities\Department;
use App\Entities\DepartmentStaff;

class StaffController extends Controller
{
    // Login required.
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $departmentStaffs = DepartmentStaff::with('staff', 'department')->get();
        return view('staffs.index', compact('departmentStaffs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departments = Department::all();
        return view('staffs.create', compact('departments'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:50',
            'email' => 'required|email|max:50',
            'employment_date' => 'required|date',
            'department_id' => 'required',
            'is_manager' => 'required'
        ]);

        $staff = new Staff([
            'name' => $request->get('name'),
            'email' => $request->get('email'),
            'employment_date' => $request->get('employment_date')
        ]);
        $staff->save();

        $departmentstaff = new DepartmentStaff([
            'staffId' => $staff->id,
            'departmentId' => $request->get('department_id'),
            'isManager' => $this->requestBoolVal($request->get('is_manager'))
        ]);
        $departmentstaff->save();

        return redirect('/staffs')->with('success', 'staff saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data =  array();
        $staff = Staff::find($id);
        $departments = Department::all();
        $departmentstaff = DepartmentStaff::where('staffId', $staff->id)->first();

        return view('staffs.edit', compact('staff', 'departments', 'departmentstaff'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|string|max:50',
            'email' => 'required|email|max:50',
            'employment_date' => 'required|date',
            'departmentstaff_id' => 'required',
            'department_id' => 'required',
            'is_manager' => 'required'
          ]);
    
        $staff = Staff::find($id);
        $staff->name = $request->get('name');
        $staff->email = $request->get('email');
        $staff->employment_date = $request->get('employment_date');
        $staff->save();

        $departmentstaff = DepartmentStaff::find($request->get('departmentstaff_id'));
        $departmentstaff->staffId = $id;
        $departmentstaff->departmentId = $request->get('department_id');
        $departmentstaff->isManager = $this->requestBoolVal($request->get('is_manager'));
        $departmentstaff->save();

        return redirect('/staffs')->with('success', 'Staff has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $staff = Staff::find($id);
        $staff->delete();
        DepartmentStaff::where('staffId', $id)->delete();
        return redirect('/staffs')->with('success', 'Staff has been deleted Successfully');
    }

    private function requestBoolVal($val)
    {
        if ($val == 'y') {
            $val = 1;
        } else {
            $val = 0;
        }
        return $val;
    }
}

resources/views/staffs/create.blade.php
@extends('layouts.web')

@section('web-header')
<div>Add Staff</div>
@endsection

@section('web-content')
@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div><br />
@endif
<form method="post" action="{{ route('staffs.store') }}">
    <div class="form-group">
        @csrf
        <label for="name">Staff Name:</label>
        <input type="text" class="form-control" name="name" required/>
    </div>
    <div class="form-group">
        <label for="price">Staff Email:</label>
        <input type="text" class="form-control" name="email" required/>
    </div>
    <div class="form-group">
        <label for="quantity">Date of employment:</label>
        <input type="date" class="form-control" name="employment_date" required/>
    </div>
    <div class="form-group">
            <label for="department">Department:</label>
            <select name="department_id" class="form-control">
            @foreach($departments as $department)
                <option value="{{$department->id}}">{{$department->name}}</option>
            @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="manager">Manager?</label>
            <select name="is_manager"  class="form-control">
                <option value="y">Yes</option>
                <option value="n">No</option>
            </select>
        </div>
    <button type="submit" class="btn btn-primary">Add</button>
</form>
@endsection

resources/views/staffs/edit.blade.php
@extends('layouts.web')

@section('web-header')
<div>Edit Staff</div>
@endsection

@section('web-content')
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div><br />
    @endif
    <form method="post" action="{{ route('staffs.update', $staff->id) }}">
        @method('PATCH')
        @csrf
        <input type="hidden" class="form-control" name="departmentstaff_id" value="{{ $departmentstaff->id }}" />
        <div class="form-group">
            <label for="name">Staff Name:</label>
            <input type="text" class="form-control" name="name" value="{{ $staff->name }}" />
        </div>
        <div class="form-group">
            <label for="email">Staff Email:</label>
            <input type="text" class="form-control" name="email" value="{{ $staff->email }}" />
        </div>
        <div class="form-group">
            <label for="employment">Date of employment:</label>
            <input type="date" class="form-control" name="employment_date" value={{ $staff->employment_date }} />
        </div>
        <div class="form-group">
            <label for="department">Department:</label>
            <select name="department_id" class="form-control">
            @foreach($departments as $department)
                <option value="{{$department->id}}" @if ($departmentstaff->departmentId === $department->id) selected="selected" @endif>{{$department->name}}</option>
            @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="manager">Manager?</label>
            <select name="is_manager"  class="form-control">
                <option value="y" @if ($departmentstaff->isManager === 1) selected="selected" @endif>Yes</option>
                <option value="n" @if ($departmentstaff->isManager === 0) selected="selected" @endif>No</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
@endsection

resources/views/staffs/index.blade.php
@extends('layouts.web')

@section('web-header')
<div>Staff List</div>
@endsection

@section('web-content')
@if(session()->get('success'))
    <div class="alert alert-success">
        {{ session()->get('success') }}  
    </div><br />
@endif
<table class="table table-striped">
    <thead>
        <tr>
        <td>ID</td>
        <td>Name</td>
        <td>Email</td>
        <td>Date of employment</td>
        <td>Department Name</td>
        <td>Is Manager</td>
        <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
    @foreach($departmentStaffs as $departmentStaff)
        <tr>
            <td>{{$departmentStaff->staff->id}}</td>
            <td>{{$departmentStaff->staff->name}}</td>
            <td>{{$departmentStaff->staff->email}}</td>
            <td>{{$departmentStaff->staff->employment_date}}</td>
            <td>{{$departmentStaff->department->name}}</td>
            <td>
            @if ($departmentStaff->isManager === 1)
                <p class="text-success">Yes</p>
            @else
                <p class="text-danger">No</p>
            @endif
            </td>
            <td><a href="{{ route('staffs.edit',$departmentStaff->staff->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('staffs.destroy', $departmentStaff->staff->id)}}" method="post">
                @csrf
                @method('DELETE')
                <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
<div>
@endsection