routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('staffs', 'StaffController');
Route::resource('departments', 'DepartmentController');

Route::get('reports/departmentStafflist', 'DepartmentStaffController@index')->name('reports.departmentStaffList');

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Entities\Department;

class DepartmentController extends Controller
{
    // Login required.
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('departments.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('departments.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:50',
            'description' => 'required|string|max:50'
        ]);

        $department = new Department([
            'name' => $request->get('name'),
            'description' => $request->get('description')
        ]);

        $department->save();

        return redirect('/departments')->with('success', 'Department saved!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $department = Department::find($id);
        return view('departments.edit', compact('department'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|string|max:50',
            'description' => 'required|string|max:50'
        ]);

        $department = new Department([
            'name' => $request->get('name'),
            'description' => $request->get('description')
        ]);

        $department = Department::find($id);
        $department->name = $request->get('name');
        $department->description = $request->get('description');

        $department->save();

        return redirect('/departments')->with('department', 'Department has been updated');
    }
}

resources/views/departments/create.blade.php
@extends('layouts.web')

@section('web-header')
<div>Add Department</div>
@endsection

@section('web-content')
@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div><br />
@endif
<form method="post" action="{{ route('departments.store') }}">
    <div class="form-group">
        @csrf
        <label for="name">Department Name:</label>
        <input type="text" class="form-control" name="name" required/>
    </div>
    <div class="form-group">
        <label for="price">Department Description:</label>
        <input type="text" class="form-control" name="description" required/>
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
</form>
@endsection

resources/views/departments/edit.blade.php
@extends('layouts.web')

@section('web-header')
<div>Department Edit</div>
@endsection

@section('web-content')
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div><br />
    @endif
    <form method="post" action="{{ route('departments.update', $department->id) }}">
        @method('PATCH')
        @csrf
        <div class="form-group">
        <label for="name">Department Name:</label>
        <input type="text" class="form-control" name="name" value="{{ $department->name }}" />
        </div>
        <div class="form-group">
        <label for="price">Department Description:</label>
        <input type="text" class="form-control" name="description" value="{{ $department->description }}" />
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
@endsection

resources/views/departments/index.blade.php
@extends('layouts.webReact')

@section('web-header')
<div>Department List</div>
@endsection

@section('web-content')
<body>
    <div id="department-list"></div>
    <script src="{{ asset('js/app.js') }}"></script>
</body>
@endsection